### ISSUE TITLE
Missing python file

### ISSUE THREAD

**Issue by teras** [Jesssullivan/clipi#1]
Hello!
I was trying to use your instructions but failed :( 
It seems that the file 
```https://raw.githubusercontent.com/Jesssullivan/USBoN/master/QEMU_Raspian.py```
does not exist any more.
Any help?

**Comment by Jesssullivan** [comment]
Hey, yeah- for now I'd do the following from a shell to get running quickly with raspbian via qemu:  
```
# make sure you've got qemu-arm and wget-
# for ubuntu:
sudo apt-get install qemu-system-arm -y
# or osx:
brew install qemu wget 

# snag the kernel bits:
wget https://raw.githubusercontent.com/dhruvvyas90/qemu-rpi-kernel/master/kernel-qemu-4.14.79-stretch -O kernel-qemu-4.14.79-stretch 
# (this one may take a while):
wget https://raw.githubusercontent.com/dhruvvyas90/qemu-rpi-kernel/master/versatile-pb.dtb -O versatile-pb.dtb

# get an image:
wget http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2018-11-15/2018-11-13-raspbian-stretch-lite.zip

# unzip the zipped image:
unzip "2018-11-13-raspbian-stretch-lite.zip" 

# convert to qcow for qemu goodness:
qemu-img convert -f raw -O qcow2 2018-11-13-raspbian-stretch-lite.img stretchlite.qcow2 && qemu-img resize stretchlite.qcow2 +8G

# launch from qcow:
qemu-system-arm -kernel kernel-qemu-4.14.79-stretch -cpu arm1176 -m 256 -M versatilepb -dtb versatile-pb.dtb -no-reboot -serial stdio -append "root=/dev/sda2 panic=1 rootfsrtype=ext4 rw" -hda stretchlite.qcow2
```
Cheers!
-Jess

**Comment by Jesssullivan** [comment]
Hmm, going through it appears this repo is quite broken.  Sorry mate!    Perhaps best to stick with qemu from the shell (as above) for now.

**Comment by teras** [comment]
Thanks!
It properly works if I follow the steps.
What if you bring this information to the frontpage?

I was looking for the last 2 days a way to do this on my mac, and these instructions were the first to actually work.

Also, what about the files that got downloaded from dhruvvyas90 ? Maybe these files will rotten (like similar examples...) What if you keep a backup to your repository?

Just my thoughts :)

**Comment by Jesssullivan** [comment]
Thanks- updated the master for now.  Cheers!
